# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def base_pods
    # Pods for meli-mobile-challenge
    pod 'Moya/RxSwift', '~> 14.0.0'
    pod 'RxCocoa', '~> 5.1.1'
    pod 'RxCodable', '~> 1.0.0'
    pod 'RxDataSources', '~> 4.0.1'
    pod 'IQKeyboardManagerSwift', '~> 6.5.5'
    pod 'R.swift', '~> 5.2.2'
    pod 'Kingfisher', '~> 5.14.0'
    pod 'NVActivityIndicatorView', '~> 4.8.0'
end

target 'meli-mobile-challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  base_pods

  # Pods for meli-mobile-challenge

  target 'meli-mobile-challengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'meli-mobile-challengeUITests' do
    # Pods for testing
  end

end
